title: Ashley Thoo # your name (or website title) here

logo: "/images/ashley-photo.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/ashleythy/">LinkedIn</a> |
  <a href="https://github.com/ashleythy">GitHub</a>
  </p>
  
  <p align="justify">
  Data enthusiast in the field of global public health
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
